### ISSUE TITLE
NLTK dependency requires NLTK Data

### ISSUE THREAD

**Issue by lewismc** [joshua-decoder/joshua_translation_engine#13]
If I run the server as follows
```
lmcgibbn@LMC-032857 /usr/local/joshua_translation_engine(master) $ python app.py -b /usr/local/Cellar/joshua/HEAD/libexec/language-pack-es-en-phrase-2015-03-06/ -s es -t en -p 5674
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
    server-port: 5674
```
and then i hit it with the following CURL request
```
curl http://localhost:5000/joshua/translate/english -i -H "Content-Type: application/json" -X POST -d '{"inputLanguage": "Spanish", "inputText": "vuelo"}' -v
```
I get the following trace
```
127.0.0.1 - - [28/Apr/2016 12:49:56] "POST /joshua/translate/english HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/joshua_translation_engine/app.py", line 34, in post
    input_text = PreProcessor(source_lang).prepare(args['inputText'])
  File "/usr/local/joshua_translation_engine/text.py", line 81, in __init__
    'tokenizers/punkt/%s.pickle' % lang_aliases.long_english_name
  File "/Library/Python/2.7/site-packages/nltk/data.py", line 801, in load
    opened_resource = _open(resource_url)
  File "/Library/Python/2.7/site-packages/nltk/data.py", line 919, in _open
    return find(path_, path + ['']).open()
  File "/Library/Python/2.7/site-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource u'tokenizers/punkt/spanish.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/Users/lmcgibbn/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
**********************************************************************
```
This can be resolved by executing the following  the [NLTK data command line installation](http://www.nltk.org/data.html#command-line-installation)
```
sudo python -m nltk.downloader -d /usr/local/share/nltk_data all
```
This needs to be mentioned on the README or somewhere else.

**Comment by lewismc** [comment]
Thanks @mjpost
