### ISSUE TITLE
penn-tree-(de)tokenizer.perl no longer exists

### ISSUE THREAD

**Issue by lewismc** [joshua-decoder/joshua_translation_engine#15]
Hi Folks,
I am seeing a bug in [text.py](https://github.com/joshua-decoder/joshua_translation_engine/blob/master/text.py#L11-L15)
When I submit the following request
```
curl http://localhost:5000/joshua/translate/english -i -H "Content-Type: application/json" -X POST -d '{"inputLanguage": "spanish", "inputText": "Junqueras admite cierto deshielo pero sale del encuentro con Sáenz Santamaría sin acuerdos."}' -v
```
This results in the following
```
127.0.0.1 - - [28/Apr/2016 13:59:32] "POST /joshua/translate/english HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/joshua_translation_engine/app.py", line 34, in post
    input_text = PreProcessor(source_lang).prepare(args['inputText'])
  File "/usr/local/joshua_translation_engine/text.py", line 92, in prepare
    tokenized_sentences = tokenize(self._lang.short_name, sentences)
  File "/usr/local/joshua_translation_engine/text.py", line 59, in tokenize
    return _penn_treebank_tokenize(lang_short_code, text)
  File "/usr/local/joshua_translation_engine/text.py", line 23, in _penn_treebank_tokenize
    env=os.environ
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
This has to do with the script being removed between [6.0.4](https://github.com/joshua-decoder/joshua/blob/v6.0.4/scripts/training/penn-treebank-tokenizer.perl) and current master branch... was this renamed and moved somewhere else or was it just deleted? Does anyone know? Thanks

**Comment by lewismc** [comment]
The same is true for [penn-treebank-detokenizer.perl](https://github.com/joshua-decoder/joshua_translation_engine/blob/master/text.py#L35)

**Comment by lewismc** [comment]
Once I add both of those files I am able to do my translation no problems
```
$ curl http://localhost:5000/joshua/translate/english -i -H "Content-Type: application/json" -X POST -d '{"inputLanguage": "spanish", "inputText": "Junqueras admite cierto deshielo pero sale del encuentro con Sáenz Santamaría sin acuerdos."}' -v
* Adding handle: conn: 0x7fa07b800000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fa07b800000) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 5000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> POST /joshua/translate/english HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:5000
> Accept: */*
> Content-Type: application/json
> Content-Length: 138
>
* upload completely sent off: 138 out of 138 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 201 CREATED
HTTP/1.0 201 CREATED
< Content-Type: application/json
Content-Type: application/json
< Content-Length: 126
Content-Length: 126
< Server: Werkzeug/0.11.9 Python/2.7.5
Server: Werkzeug/0.11.9 Python/2.7.5
< Date: Thu, 28 Apr 2016 21:25:04 GMT
Date: Thu, 28 Apr 2016 21:25:04 GMT

<
{
    "outputText": "Junqueras admits true thaw but out of the meeting with s\u00e1enz santamar\u00eda without agreements."
}
* Closing connection 0
```

**Comment by lewismc** [comment]
This issue has been reported over on https://github.com/apache/incubator-joshua/pull/8, it will be resolved over there.

**Comment by mjpost** [comment]
just saw this. it was moved under scripts/preprocessing/tokenize.pl

**Comment by lewismc** [comment]
Can you please commit the fix for this?

**Comment by mjpost** [comment]
Well, if you're using a release version of Joshua, I believe 6.0.5 still has the old script location. Do you still want me to update it?

**Comment by lewismc** [comment]
I'm always running off of Joshua master
We have our translation services running at xdata.jpl.nasa.gov/translate and this server has made it much easier to deploy services this week. 
If you could update it, it would be very much appreciated.
Thanks @mjpost

**Comment by mjpost** [comment]
Should be fixed. A few things --- this should also be calling the normalizer, which does things like standardize punctuation. I will add that soon when I get to this project.
